In [1]:
import pandas as pd

In [50]:
pd.__version__

'3.0.5'

In [2]:
df=pd.read_csv("01-intro/car_fuel_efficiency_2026.csv")

In [52]:
df.model_year.count()

np.int64(10000)

In [53]:
df.fuel_type.nunique()

3

In [5]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [6]:
df.groupby('origin').fuel_efficiency_mpg.max()

origin
Asia      41.2
Europe    39.4
USA       38.2
Name: fuel_efficiency_mpg, dtype: float64

In [7]:
df.horsepower.median()

np.float64(254.0)

In [8]:
df.groupby('horsepower').horsepower.count().sort_values(ascending=False)

horsepower
252.0    174
246.0    168
256.0    168
253.0    165
259.0    165
        ... 
320.0      1
322.0      1
327.0      1
328.0      1
330.0      1
Name: horsepower, Length: 153, dtype: int64

In [9]:
df.horsepower=df.horsepower.fillna(0)

In [10]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower               0
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [11]:
df.groupby('horsepower').horsepower.count().sort_values(ascending=False)

horsepower
0.0      877
252.0    174
246.0    168
256.0    168
253.0    165
        ... 
320.0      1
322.0      1
327.0      1
328.0      1
330.0      1
Name: horsepower, Length: 154, dtype: int64

In [12]:
df.horsepower.median()

np.float64(252.0)

In [13]:
df_asia=df[
    df.origin=="Asia" 
]

In [14]:
df_asia_vehicle_weight_model_year=df_asia[["vehicle_weight","model_year"]]

In [15]:
df_first_seven=df_asia_vehicle_weight_model_year.head(n=7)

In [16]:
X=df_first_seven.values

In [17]:
XT=X.T

In [18]:
import numpy as np

In [19]:
def calculate_vector_vector_multiplication(a,b):
    assert a.shape[0]==b.shape[0]
    result=0.0
    shape=a.shape[0]

    for i in range(shape):
        result+= a[i]*b[i]

    return result

def calculate_matrix_vector_multiplication(U,v):
    assert U.shape[1]==v.shape[0]
    num_rows=U.shape[0]
    result=np.zeros(num_rows)

    for i in range(num_rows):
        result[i]=calculate_vector_vector_multiplication(U[i],v)

    return result


def matrix_matrix_multiplication(U,V):
    assert U.shape[1]==V.shape[0]

    num_rows=U.shape[0]
    num_cols=V.shape[1]

    result=np.zeros((num_rows,num_cols))

    for i in range(num_cols):
        vi=V[:,i]

        result[:,i]=calculate_matrix_vector_multiplication(U,vi)
    return result

    

In [49]:
print(X.shape)
print(XT.shape)
print(X)
print(XT)


(7, 2)
(2, 7)
[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]
[[4240 4310 4230 4420 3950 4750 4450]
 [1996 1992 1997 1978 2007 2021 2019]]


In [31]:
XTX = matrix_matrix_multiplication(XT, X)

In [32]:
XTX

array([[1.3195050e+08, 6.0750580e+07],
       [6.0750580e+07, 2.8041424e+07]])

In [33]:
XTX.shape


(2, 2)

In [34]:
XTX_inv=np.linalg.inv(XTX)

In [35]:
y=np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [39]:

r1=matrix_matrix_multiplication(XTX_inv,XT)



In [46]:
r1.shape

(2, 7)

In [47]:
y.shape

(7,)

In [42]:
w = calculate_matrix_vector_multiplication(r1, y)

In [44]:
w.sum()

np.float64(0.3691969690492522)