In [2]:
import numpy as np

In [4]:
# creating arrays

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(10,4.5)

array([4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5])

In [8]:
a=np.array([1,2,3,4,5,6,7])

In [9]:
a[2]

np.int64(3)

In [10]:
a[2]=23

In [11]:
a

array([ 1,  2, 23,  4,  5,  6,  7])

In [12]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [14]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [15]:
# multidimension arrays

In [16]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [19]:
b[2][1]

np.int64(8)

In [20]:
b[2][1]=872

In [21]:
b

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7, 872,   9]])

In [22]:
b[1]=[2,5,6]

In [23]:
b

array([[  1,   2,   3],
       [  2,   5,   6],
       [  7, 872,   9]])

In [24]:
b[:,2]

array([3, 6, 9])

In [25]:
b[:,2]=[6,4,3]

In [26]:
b

array([[  1,   2,   6],
       [  2,   5,   4],
       [  7, 872,   3]])

In [27]:
#randomly generated arrays

In [28]:
np.random.rand(4,5)

array([[0.41236316, 0.08190421, 0.5459624 , 0.85020757, 0.19877525],
       [0.83973857, 0.19194436, 0.17524031, 0.73854312, 0.33486292],
       [0.54643721, 0.44179979, 0.311314  , 0.37249991, 0.56740828],
       [0.15093539, 0.95992864, 0.03615646, 0.70267245, 0.09945745]])

In [29]:
np.random.seed(2)

In [30]:
100*np.random.rand(4,5)

array([[43.59949021,  2.59262318, 54.96624779, 43.53223926, 42.03678021],
       [33.0334821 , 20.4648634 , 61.92709664, 29.96546737, 26.68272751],
       [62.11338328, 52.91420943, 13.45799453, 51.35781213, 18.44398656],
       [78.53351478, 85.39752926, 49.42368374, 84.65614854,  7.9645477 ]])

In [31]:
np.random.seed(2)

In [32]:
100*np.random.randn(4,5)

array([[ -41.67578474,   -5.62668272, -213.61960957,  164.02708084,
        -179.34355852],
       [ -84.17473657,   50.28814172, -124.52880866, -105.79522189,
         -90.90076149],
       [  55.14540445,  229.22080128,    4.1539393 , -111.79254451,
          53.90583206],
       [ -59.61596998,   -1.91304965,  117.50012195,  -74.78709493,
           0.9025251 ]])

In [33]:
np.random.seed(2)

In [34]:
np.random.randint(low=0,high=100,size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [35]:
a=np.arange(5)

In [36]:
a+2

array([2, 3, 4, 5, 6])

In [37]:
a*2

array([0, 2, 4, 6, 8])

In [38]:
b = (10 + (a * 2)) ** 2 / 100

In [39]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [40]:
a+b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [41]:
e=np.arange(5)

In [54]:
e

array([0, 1, 2, 3, 4])

In [42]:
f=np.arange(5)

In [43]:
f

array([0, 1, 2, 3, 4])

In [44]:
e+f

array([0, 2, 4, 6, 8])

In [45]:
f >= 2

array([False, False,  True,  True,  True])

In [46]:
e=e+2

In [47]:
e

array([2, 3, 4, 5, 6])

In [48]:
f

array([0, 1, 2, 3, 4])

In [49]:
e[2]=1

In [50]:
e

array([2, 3, 1, 5, 6])

In [51]:
f

array([0, 1, 2, 3, 4])

In [52]:
f[f>e]

array([2])

In [54]:
f[1]=-23

In [55]:
f.min()

np.int64(-23)

In [56]:
f[3]=4

In [57]:
f.max()

np.int64(4)

In [58]:
f

array([  0, -23,   2,   4,   4])

In [59]:
f.mean()

np.float64(-2.6)

In [60]:
f.std()

np.float64(10.3072789813801)

In [6]:
u=np.array([1,2,3,4,5,6])
u+2


array([3, 4, 5, 6, 7, 8])

In [26]:
v=np.array([2,2,2,2,2,2])

In [30]:
v.shape

(6,)

In [9]:
u+v

array([3, 4, 5, 6, 7, 8])

In [66]:
def calculate_vector_vector_multiplication(a,b):
    assert a.shape[0]==b.shape[0]
    result=0.0
    shape=a.shape[0]

    for i in range(shape):
        result+= a[i]*b[i]

    return result

In [67]:
calculate_vector_vector_multiplication(u,v)

np.float64(42.0)

In [68]:
u.dot(v)

np.int64(42)

In [69]:
U = np.array([
  [2, 4, 5, 6],
  [1, 2, 1, 2],
 [3, 1, 2, 1],
])

In [70]:
U.shape

(3, 4)

In [71]:
v1=np.array([1,2,3,4])

In [72]:
def calculate_matrix_vector_multiplication(U,v):
    assert U.shape[1]==v.shape[0]
    num_rows=U.shape[0]
    result=np.zeros(num_rows)

    for i in range(num_rows):
        result[i]=calculate_vector_vector_multiplication(U[i],v)

    return result
    

In [73]:
calculate_matrix_vector_multiplication(U,v1)

array([49., 16., 15.])

In [65]:
U.dot(v1)

array([49, 16, 15])

In [74]:
V = np.array([
[1, 1, 2],
[0, 0.5, 1], 
[0, 2, 1],
[2, 1, 0],
])

In [77]:
U.shape[1]

4

In [78]:
V.shape[0]

4

In [79]:
def matrix_matrix_multiplication(U,V):
    assert U.shape[1]==V.shape[0]

    num_rows=U.shape[0]
    num_cols=V.shape[1]

    result=np.zeros((num_rows,num_cols))

    for i in range(num_cols):
        vi=V[:,i]

        result[:,i]=calculate_matrix_vector_multiplication(U,vi)
    return result

    

In [80]:
matrix_matrix_multiplication(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [81]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [82]:
I=np.eye(3)

In [83]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [84]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [86]:
Vs=V[[0,1,2]]


In [1]:
Vs_inv=np.linalg.inv(Vs)

NameError: name 'np' is not defined

In [88]:
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [89]:
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [90]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])